/* Generated By:JJTree: Do not edit this line. ASTAssignment.java */

package org.apache.commons.jexl.parser;

import org.apache.commons.jexl.JexlContext;

/**
 * x = y, assigns a value to a variable in the context.
 * @author Dion Gillard
 *
 */
public class ASTAssignment extends SimpleNode {
  public ASTAssignment(int id) {
    super(id);
  }

  public ASTAssignment(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  /**
   * Handle assignment ( left = right ) 
   */
  public Object value(JexlContext context) throws Exception
  {
      // left should be the variable (reference) to assign to
      SimpleNode left = (SimpleNode)jjtGetChild(0);
      // right should be the expression to evaluate
      Object right = ((SimpleNode) jjtGetChild(1)).value(context);
      if (left instanceof ASTReference) {
          ASTReference reference = (ASTReference)left;
          left = (SimpleNode)reference.jjtGetChild(0);
          if (left instanceof ASTIdentifier) {
              String identifier = ((ASTIdentifier)left).getIdentifierString();
              context.getVars().put(identifier,right);
          }
      }
      return right;
  }
}