/* Generated By:JJTree: Do not edit this line. ASTBitwiseAndNode.java */

package org.apache.commons.jexl.parser;

public class ASTBitwiseAndNode extends SimpleNode {
  public ASTBitwiseAndNode(int id) {
    super(id);
  }

  public ASTBitwiseAndNode(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
