/* Generated By:JJTree: Do not edit this line. ASTBitwiseOrNode.java */

package org.apache.commons.jexl.parser;

public class ASTBitwiseOrNode extends SimpleNode {
  public ASTBitwiseOrNode(int id) {
    super(id);
  }

  public ASTBitwiseOrNode(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
