/* Generated By:JJTree: Do not edit this line. ASTBitwiseComplNode.java */

package org.apache.commons.jexl.parser;

public class ASTBitwiseComplNode extends SimpleNode {
  public ASTBitwiseComplNode(int id) {
    super(id);
  }

  public ASTBitwiseComplNode(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
