/* Generated By:JJTree: Do not edit this line. ASTBitwiseXorNode.java */

package org.apache.commons.jexl.parser;

public class ASTBitwiseXorNode extends SimpleNode {
  public ASTBitwiseXorNode(int id) {
    super(id);
  }

  public ASTBitwiseXorNode(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
