/* Generated By:JJTree: Do not edit this line. ASTJexlScript.java */

package org.apache.commons.jexl.parser;

import org.apache.commons.jexl.JexlContext;

/**
 * Top of the syntax tree - parsed Jexl code.
 * @since 1.1
 */
public class ASTJexlScript extends SimpleNode {
  public ASTJexlScript(int id) {
    super(id);
  }

  public ASTJexlScript(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public Object value(JexlContext jc) throws Exception
  {
      SimpleNode child = (SimpleNode)jjtGetChild(0);
      return child.value(jc);
  }
}
