/* Generated By:JJTree: Do not edit this line. ASTJexlScript.java */

package org.apache.commons.jexl.parser;

public class ASTJexlScript extends SimpleNode {
  public ASTJexlScript(int id) {
    super(id);
  }

  public ASTJexlScript(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
