/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Generated By:JJTree: Do not edit this line. ASTMapEntry.java */

package org.apache.commons.jexl.parser;

import org.apache.commons.jexl.JexlContext;

public class ASTMapEntry extends SimpleNode {
    public ASTMapEntry( int id ) {
        super( id );
    }

    public ASTMapEntry( Parser p, int id ) {
        super( p, id );
    }

    /** Accept the visitor. * */
    public Object jjtAccept( ParserVisitor visitor, Object data ) {
        return visitor.visit( this, data );
    }

    public Object value( JexlContext context ) throws Exception {
        return new Object[]{ ( (SimpleNode) jjtGetChild( 0 ) ).value( context ),
                             ( (SimpleNode) jjtGetChild( 1 ) ).value( context ) };
    }
}
