/* Generated By:JJTree: Do not edit this line. ASTReferenceExpression.java */

package org.apache.commons.jexl.parser;

public class ASTReferenceExpression extends SimpleNode {
  public ASTReferenceExpression(int id) {
    super(id);
  }

  public ASTReferenceExpression(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
