/* Generated By:JJTree: Do not edit this line. ASTReferenceExpression.java */

package org.apache.commons.jexl.parser;

import org.apache.commons.jexl.JexlContext;

/**
 * variable; A reference by itself.
 */
public class ASTReferenceExpression extends SimpleNode {
  public ASTReferenceExpression(int id) {
    super(id);
  }

  public ASTReferenceExpression(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  /**
   * @return the value of the expression 
   */
  public Object value(JexlContext context) throws Exception
  {
      return ((SimpleNode) jjtGetChild(0)).value(context);
  }
}
