/* Generated By:JJTree: Do not edit this line. ASTWhileStatement.java */
/*
 * Copyright 2002,2004 The Apache Software Foundation.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.commons.jexl.parser;

import org.apache.commons.jexl.JexlContext;
import org.apache.commons.jexl.util.Coercion;

/**
 * A while loop.
 * Syntax:
 *      while ( expression ) statement
 * 
 * @author Dion Gillard
 * @since 1.0.1
 */
public class ASTWhileStatement extends SimpleNode {
    public ASTWhileStatement(int id) {
        super(id);
    }

    public ASTWhileStatement(Parser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(ParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public Object value(JexlContext jc) throws Exception {
        Object result = null;
        /* first child is the expression */
        SimpleNode expressionNode = (SimpleNode) jjtGetChild(0); 
        while (Coercion.coerceBoolean(expressionNode.value(jc)).booleanValue()) {
            // execute statement
            result = ((SimpleNode) jjtGetChild(1)).value(jc);
        }

        return result;
    }

}
