/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package org.apache.commons.jexl.parser;

public interface ParserConstants {

  int EOF = 0;
  int COMMENT = 1;
  int INTEGER_LITERAL = 7;
  int FLOAT_LITERAL = 8;
  int IDENTIFIER = 59;
  int LETTER = 60;
  int DIGIT = 61;
  int STRING_LITERAL = 62;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<COMMENT>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<INTEGER_LITERAL>",
    "<FLOAT_LITERAL>",
    "\"{\"",
    "\"}\"",
    "\"empty\"",
    "\"(\"",
    "\")\"",
    "\"size\"",
    "\"=\"",
    "\"||\"",
    "\"or\"",
    "\"&&\"",
    "\"and\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"eq\"",
    "\"!=\"",
    "\"ne\"",
    "\"<\"",
    "\"lt\"",
    "\">\"",
    "\"gt\"",
    "\"<=\"",
    "\"le\"",
    "\">=\"",
    "\"ge\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"div\"",
    "\"%\"",
    "\"mod\"",
    "\"~\"",
    "\"!\"",
    "\"not\"",
    "\"null\"",
    "\"true\"",
    "\"false\"",
    "\";\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"foreach\"",
    "\"in\"",
    "\"[\"",
    "\",\"",
    "\"]\"",
    "\"=>\"",
    "\".\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<STRING_LITERAL>",
  };

}
