/* Generated By:JJTree: Do not edit this line. ./ParserTreeConstants.java */

package org.apache.commons.jexl.parser;

public interface ParserTreeConstants
{
  public int JJTJEXLSCRIPT = 0;
  public int JJTBLOCK = 1;
  public int JJTEMPTYFUNCTION = 2;
  public int JJTSIZEFUNCTION = 3;
  public int JJTIDENTIFIER = 4;
  public int JJTEXPRESSION = 5;
  public int JJTASSIGNMENT = 6;
  public int JJTVOID = 7;
  public int JJTORNODE = 8;
  public int JJTANDNODE = 9;
  public int JJTBITWISEORNODE = 10;
  public int JJTBITWISEXORNODE = 11;
  public int JJTBITWISEANDNODE = 12;
  public int JJTEQNODE = 13;
  public int JJTNENODE = 14;
  public int JJTLTNODE = 15;
  public int JJTGTNODE = 16;
  public int JJTLENODE = 17;
  public int JJTGENODE = 18;
  public int JJTADDNODE = 19;
  public int JJTSUBTRACTNODE = 20;
  public int JJTMULNODE = 21;
  public int JJTDIVNODE = 22;
  public int JJTMODNODE = 23;
  public int JJTUNARYMINUSNODE = 24;
  public int JJTBITWISECOMPLNODE = 25;
  public int JJTNOTNODE = 26;
  public int JJTNULLLITERAL = 27;
  public int JJTTRUENODE = 28;
  public int JJTFALSENODE = 29;
  public int JJTINTEGERLITERAL = 30;
  public int JJTFLOATLITERAL = 31;
  public int JJTSTRINGLITERAL = 32;
  public int JJTEXPRESSIONEXPRESSION = 33;
  public int JJTSTATEMENTEXPRESSION = 34;
  public int JJTREFERENCEEXPRESSION = 35;
  public int JJTIFSTATEMENT = 36;
  public int JJTWHILESTATEMENT = 37;
  public int JJTFOREACHSTATEMENT = 38;
  public int JJTMAPLITERAL = 39;
  public int JJTMAPENTRY = 40;
  public int JJTMETHOD = 41;
  public int JJTARRAYACCESS = 42;
  public int JJTSIZEMETHOD = 43;
  public int JJTREFERENCE = 44;


  public String[] jjtNodeName = {
    "JexlScript",
    "Block",
    "EmptyFunction",
    "SizeFunction",
    "Identifier",
    "Expression",
    "Assignment",
    "void",
    "OrNode",
    "AndNode",
    "BitwiseOrNode",
    "BitwiseXorNode",
    "BitwiseAndNode",
    "EQNode",
    "NENode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "SubtractNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "UnaryMinusNode",
    "BitwiseComplNode",
    "NotNode",
    "NullLiteral",
    "TrueNode",
    "FalseNode",
    "IntegerLiteral",
    "FloatLiteral",
    "StringLiteral",
    "ExpressionExpression",
    "StatementExpression",
    "ReferenceExpression",
    "IfStatement",
    "WhileStatement",
    "ForeachStatement",
    "MapLiteral",
    "MapEntry",
    "Method",
    "ArrayAccess",
    "SizeMethod",
    "Reference",
  };
}
