/*
 * Copyright 2002-2006 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Generated By:JJTree: Do not edit this line. ParserTreeConstants.java */

package org.apache.commons.jexl.parser;

public interface ParserTreeConstants {
    int JJTJEXLSCRIPT = 0;

    int JJTBLOCK = 1;

    int JJTEMPTYFUNCTION = 2;

    int JJTSIZEFUNCTION = 3;

    int JJTIDENTIFIER = 4;

    int JJTEXPRESSION = 5;

    int JJTASSIGNMENT = 6;

    int JJTVOID = 7;

    int JJTORNODE = 8;

    int JJTANDNODE = 9;

    int JJTBITWISEORNODE = 10;

    int JJTBITWISEXORNODE = 11;

    int JJTBITWISEANDNODE = 12;

    int JJTEQNODE = 13;

    int JJTNENODE = 14;

    int JJTLTNODE = 15;

    int JJTGTNODE = 16;

    int JJTLENODE = 17;

    int JJTGENODE = 18;

    int JJTADDNODE = 19;

    int JJTSUBTRACTNODE = 20;

    int JJTMULNODE = 21;

    int JJTDIVNODE = 22;

    int JJTMODNODE = 23;

    int JJTUNARYMINUSNODE = 24;

    int JJTBITWISECOMPLNODE = 25;

    int JJTNOTNODE = 26;

    int JJTNULLLITERAL = 27;

    int JJTTRUENODE = 28;

    int JJTFALSENODE = 29;

    int JJTINTEGERLITERAL = 30;

    int JJTFLOATLITERAL = 31;

    int JJTSTRINGLITERAL = 32;

    int JJTEXPRESSIONEXPRESSION = 33;

    int JJTSTATEMENTEXPRESSION = 34;

    int JJTREFERENCEEXPRESSION = 35;

    int JJTIFSTATEMENT = 36;

    int JJTWHILESTATEMENT = 37;

    int JJTFOREACHSTATEMENT = 38;

    int JJTMETHOD = 39;

    int JJTARRAYACCESS = 40;

    int JJTSIZEMETHOD = 41;

    int JJTREFERENCE = 42;

    String[] jjtNodeName = {"JexlScript", "Block", "EmptyFunction", "SizeFunction", "Identifier", "Expression",
        "Assignment", "void", "OrNode", "AndNode", "BitwiseOrNode", "BitwiseXorNode", "BitwiseAndNode", "EQNode",
        "NENode", "LTNode", "GTNode", "LENode", "GENode", "AddNode", "SubtractNode", "MulNode", "DivNode", "ModNode",
        "UnaryMinusNode", "BitwiseComplNode", "NotNode", "NullLiteral", "TrueNode", "FalseNode", "IntegerLiteral",
        "FloatLiteral", "StringLiteral", "ExpressionExpression", "StatementExpression", "ReferenceExpression",
        "IfStatement", "WhileStatement", "ForeachStatement", "Method", "ArrayAccess", "SizeMethod", "Reference", };
}
